pipeline:

  reverseproxy_build:
    auto_tag: true
    group: build
    image: plugins/docker
    repo: registry.fge.cloud/fabiangehrlicher/reverseproxy
    registry: https://registry.fge.cloud
    dockerfile: Dockerfile
    username: drone
    password: drone

  deploy:
    image: appleboy/drone-ssh
    host: fge.cloud
    username: root
    port: 22
    secrets: [ ssh_password ]
    script:
    - nohup cdstack-deploy &
